# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-07 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('createdOn', models.DateTimeField(blank=True, null=True)),
                ('complexity', models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six'), ('7', 'seven'), ('8', 'eight'), ('9', 'nine'), ('10', 'ten')], max_length=1)),
                ('status', models.CharField(choices=[('NEW', 'new'), ('INPROGRESS', 'inprogress'), ('RESOLVED', 'resolved'), ('FEEDBACK', 'feedback'), ('CLOSED', 'closed')], max_length=1)),
            ],
        ),
    ]
