# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 08:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160809_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createdOn',
            field=models.DateField(default=datetime.date(2016, 8, 10)),
        ),
    ]
